package SoftwarePlatforms.intentions;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

/**
 * Helper class for annotating suitable models with a software platform annotation.
 * 
 * @author Dennis Leroy Wigand (dwigand@techfak.uni-bielefeld.de)
 */
public class SoftwarePlatformAnnotationIntentionHelper {

  /**
   * Retrieve the description for the software platform to show in the context menu.
   * 
   * @author Dennis Leroy Wigand (dwigand@techfak.uni-bielefeld.de)
   * @param node suitable for annotation.
   * @param softwarePlatformString specific description from the specialized software platform.
   * @param annotationConcept to check if it is already attached.
   * @return description for the context menu.
   */
  public static String getSoftwarePlatformDescription(SNode node, String softwarePlatformString, SConcept annotationConcept) {
    String ret = "";
    if ((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x8fb3e629b68f443eL, 0xb616d61142df624bL, 0x2c5757d10fb46b85L, "SoftwarePlatforms.structure.IAmSoftwarePlatform"))) != null) && AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x8fb3e629b68f443eL, 0xb616d61142df624bL, 0x2c5757d10fb46b85L, "SoftwarePlatforms.structure.IAmSoftwarePlatform"))).getConcept().isSubConceptOf(annotationConcept)) {
      ret = "Remove " + softwarePlatformString + " (Software Platform)";
    } else {
      ret = "Use " + softwarePlatformString + " (Software Platform)";
    }
    return ret;
  }

  /**
   * Helper function to attach an annotation.
   * 
   * @author Dennis Leroy Wigand (dwigand@techfak.uni-bielefeld.de)
   * @param node suitable to be annotated.
   * @param softwarePlatformString pecific description from the specialized software platform.
   * @param annotationConcept to be instantiated.
   */
  public static void attachSoftwarePlatform(SNode node, String softwarePlatformString, SConcept annotationConcept) {
    if ((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x8fb3e629b68f443eL, 0xb616d61142df624bL, 0x2c5757d10fb46b85L, "SoftwarePlatforms.structure.IAmSoftwarePlatform"))) != null) && AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x8fb3e629b68f443eL, 0xb616d61142df624bL, 0x2c5757d10fb46b85L, "SoftwarePlatforms.structure.IAmSoftwarePlatform"))).getConcept().isSubConceptOf(annotationConcept)) {
      AttributeOperations.setAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x8fb3e629b68f443eL, 0xb616d61142df624bL, 0x2c5757d10fb46b85L, "SoftwarePlatforms.structure.IAmSoftwarePlatform")), null);
    } else if ((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x8fb3e629b68f443eL, 0xb616d61142df624bL, 0x2c5757d10fb46b85L, "SoftwarePlatforms.structure.IAmSoftwarePlatform"))) == null)) {
      SNode annotation = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(annotationConcept));
      SPropertyOperations.set(annotation, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), softwarePlatformString + " (Software Platform)");
      AttributeOperations.setAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x8fb3e629b68f443eL, 0xb616d61142df624bL, 0x2c5757d10fb46b85L, "SoftwarePlatforms.structure.IAmSoftwarePlatform")), annotation);
    }
  }

}
